# Generated by Django 3.1.7 on 2021-03-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200, null=True)),
                ('course_description', models.TextField(max_length=500, null=True)),
                ('difficulty_level', models.CharField(choices=[('beginner_level', 'Beginner Level'), ('intermediate_level', 'Intermediate Level'), ('experienced_level', 'Experienced Level')], default='beginner_level', max_length=200)),
                ('course_categories', models.CharField(choices=[('mbbs', 'MBBS'), ('bds', 'BDS'), ('loksewa', 'LokSewa')], max_length=300)),
                ('course_price', models.BigIntegerField(max_length=20)),
                ('thumbnail_url', models.CharField(max_length=2000)),
                ('video_url', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], default='youtube', max_length=2000)),
                ('course_content', models.CharField(max_length=2000)),
                ('more_information', models.IntegerField(max_length=200)),
                ('course_attachments', models.FileField(upload_to='static/uploads')),
            ],
        ),
    ]
