# Generated by Django 3.1.7 on 2021-04-04 16:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_title',
            new_name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='static/uploads/banner_image', null=True, upload_to='static/uploads'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_source',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], default='youtube', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_attachments',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_categories',
            field=models.CharField(blank=True, choices=[('choose', 'Choose Course Category'), ('mbbs', 'MBBS'), ('bds', 'BDS'), ('loksewa', 'LokSewa')], default='choose', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_content',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('beginner_level', 'Beginner Level'), ('intermediate_level', 'Intermediate Level'), ('experienced_level', 'Experienced Level')], default='beginner_level', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='more_information',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=200)),
                ('topic_description', models.TextField(max_length=200)),
                ('topic_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.course')),
            ],
        ),
    ]
