# Generated by Django 3.1.7 on 2021-04-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210404_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseTitle',
        ),
    ]
