# Generated by Django 3.1.7 on 2021-04-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_coursetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='static/uploads/banner_image.png', null=True, upload_to='static/uploads'),
        ),
    ]
