# Generated by Django 3.1.7 on 2021-04-09 00:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210405_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='more_information',
            new_name='course_duration',
        ),
        migrations.AddField(
            model_name='course',
            name='course_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Nepali', 'Nepali'), ('Hindi', 'Hindi')], default='English', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_requirements',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_categories',
            field=models.CharField(blank=True, choices=[('choose', 'Choose Course Category'), ('MBBS', 'MBBS'), ('BDS', 'BDS'), ('LokSewa', 'LokSewa')], default='choose', max_length=300, null=True),
        ),
    ]
