# Generated by Django 3.1.7 on 2021-04-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210409_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_caption',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Nepali', 'Nepali'), ('Hindi', 'Hindi')], default='English', max_length=200, null=True),
        ),
    ]
