# Generated by Django 3.1.7 on 2021-04-09 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_course_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
