# Generated by Django 3.1.7 on 2021-04-09 01:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_course_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_outcome',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
