# Generated by Django 3.1.7 on 2021-04-09 09:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_course_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_instructor',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='courseInstructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
