# Generated by Django 3.1.7 on 2021-04-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_auto_20210409_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseInstructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
