# Generated by Django 3.1.7 on 2021-04-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210409_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_content',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
