# Generated by Django 3.1.7 on 2021-04-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20210410_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
