# Generated by Django 3.1.7 on 2021-04-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210410_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
