# Generated by Django 3.1.7 on 2021-04-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20210410_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_attachments',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads'),
        ),
    ]
