# Generated by Django 3.1.7 on 2021-04-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20210410_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='topic_duration',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
