# Generated by Django 3.1.7 on 2021-04-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_coursetopic_topic_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='topic_duration',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
