# Generated by Django 3.1.7 on 2021-04-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_approved',
            field=models.CharField(choices=[('False', 'Pending'), ('True', 'Approved')], default='False', max_length=100),
        ),
    ]
