# Generated by Django 3.1.7 on 2021-04-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20210414_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_approved',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=100),
        ),
    ]
