# Generated by Django 3.1.7 on 2021-04-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20210414_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=200)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
