# Generated by Django 3.1.7 on 2021-04-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_coursesearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='topic_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
