# Generated by Django 3.1.7 on 2021-04-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20210418_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSearch',
        ),
    ]
