# Generated by Django 3.1.7 on 2021-04-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_auto_20210418_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_image',
            field=models.ImageField(default='static/uploads/user.png', upload_to='static/uploads'),
        ),
    ]
