# Generated by Django 3.1.7 on 2021-04-18 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_auto_20210418_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
