# Generated by Django 3.1.7 on 2021-04-18 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_instructor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
