# Generated by Django 3.1.7 on 2021-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0007_instructor_date_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_image',
            field=models.ImageField(upload_to='static/uploads'),
        ),
    ]
