# Generated by Django 3.1.7 on 2021-04-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='student',
        ),
    ]
